name: Build PS4 Mesa stack

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_DIR: repo

    steps:
      - uses: actions/checkout@v6
        with: 
            fetch-depth: 0
            persist-credentials: true
      - name: Deps
        run: |
          sudo apt install bubblewrap fuse3 lzip patch ostree flatpak tree
          pip install \
            buildstream \
            ruamel.yaml \
            pluginbase \
            pyparsing \
            requests \
            packaging \
            setuptools \
            wheel \
            tomlkit \
            dulwich
  
      - name: Building
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          make export-repo ARCH=x86_64 REPO=repo

      - name: Failure logs
        if: failure()
        run: |
          echo "==== BuildStream logs ===="
          tree ~/.cache/buildstream
          find ~/.cache/buildstream -name "*.rej" -exec tail -n 75 {} \;

      - name: Uploading
        uses: actions/upload-artifact@v4
        with:
          name: mesa-flatpak-repo
          path: repo/
